Repository Klebert-Engineering/simfil, pull requests merged in 2022-10, with the labels that each got.

#5 ModelNode Storage Improvements
  CMakeLists.txt
  include/simfil/model.h
  include/simfil/model/json.h
  include/simfil/segmented-vector.h
  include/simfil/value.h
  repl/repl.cpp
  src/function.cpp
  src/model.cpp
  src/model/json.cpp
  src/simfil.cpp
  test/complex.cpp
  test/simfil.cpp
Labels: bug :bug:, enhancement :star2:, feature :gift:

#6 Prevent string views from being remembered in trace result
  src/function.cpp
  src/model.cpp
Labels: bug :bug:

#10 Case-Insensitive syntax
  include/simfil/environment.h
  simfil-language.md
  src/environment.cpp
  src/simfil.cpp
  src/token.cpp
  test/simfil.cpp
  test/token.cpp
Labels: feature :gift:

#14 FieldExpr cache StringId
  src/simfil.cpp
Labels: enhancement :star2:, performance :racing_car:

#13 Model value type
  include/simfil/operator.h
  include/simfil/token.h
  include/simfil/value.h
  simfil-language.md
  src/simfil.cpp
  src/token.cpp
  src/value.cpp
  test/simfil.cpp
Labels: enhancement :star2:
