Repository Klebert-Engineering/simfil, pull requests merged in 2023-05, with the labels that each got.

#24 Publish Unit-Test results + Badge
  .github/workflows/cmake.yml
  README.md
Labels: ci :robot:

#26 Add valgrind checks (memcheck, helgrind, cachegrind)
  .github/workflows/cmake.yml
  .github/workflows/coverage.yml
Labels: ci :robot:

#30 Performance Tests [post arena]
  .github/workflows/cmake.yml
  .github/workflows/coverage.yml
  include/simfil/environment.h
  include/simfil/expression.h
  include/simfil/ext-geo.h
  include/simfil/function.h
  include/simfil/model/arena.h
  include/simfil/result.h
  src/ext-geo.cpp
  src/function.cpp
  src/simfil.cpp
  test/CMakeLists.txt
  test/performance.cpp
Labels: enhancement :star2:

#36 Return static string references if possible
  include/simfil/operator.h
Labels: performance :racing_car:

#37 Use final to allow for better optimization
  include/simfil/model/nodes.h
  include/simfil/overlay.h
  include/simfil/result.h
Labels: performance :racing_car:

#23 Heap-alloc-free Model Nodes, Growable Model Containers
  .github/workflows/cmake.yml
  .github/workflows/coverage.yml
  .gitignore
  CMakeLists.txt
  include/simfil/environment.h
  include/simfil/expression.h
  include/simfil/ext-geo.h
  include/simfil/function.h
  include/simfil/model.h
  include/simfil/model/arena.h
  include/simfil/model/fields.h
  include/simfil/model/json.h
  include/simfil/model/model.h
  include/simfil/model/nodes.h
  include/simfil/model/point.h
  include/simfil/operator.h
  include/simfil/overlay.h
  include/simfil/result.h
  include/simfil/simfil.h
  include/simfil/transient.h
  include/simfil/typed-meta-type.h
  include/simfil/value.h
  repl/repl.cpp
  src/environment.cpp
  src/ext-geo.cpp
  src/function.cpp
  src/model.cpp
  src/model/fields.cpp
  src/model/json.cpp
  src/model/model.cpp
  src/model/nodes.cpp
  src/overlay.cpp
  src/simfil.cpp
  src/types.cpp
  src/value.cpp
  test/CMakeLists.txt
  test/arena.cpp
  test/complex.cpp
  test/ext-geo.cpp
  test/performance.cpp
  test/simfil.cpp
Labels: feature :gift:

#32 ModelPool Serialization
  CMakeLists.txt
  include/simfil/model/arena.h
  include/simfil/model/bitsery-traits.h
  include/simfil/model/fields.h
  include/simfil/model/model.h
  include/simfil/model/nodes.h
  src/model/fields.cpp
  src/model/model.cpp
  test/arena.cpp
  test/complex.cpp
Labels: feature :gift:

#40 Add Geometry/GeometryCollection forEachPoint/forEachGeometry
  include/simfil/model/arena.h
  include/simfil/model/model.h
  include/simfil/model/nodes.h
  include/simfil/overlay.h
  src/model/fields.cpp
  src/model/model.cpp
  src/model/nodes.cpp
  src/overlay.cpp
  test/ext-geo.cpp
  test/performance.cpp
  test/simfil.cpp
Labels: feature :gift:, performance :racing_car:
