Repository Klebert-Engineering/simfil, pull requests merged in 2023-06, with the labels that each got.

#41 Update & Improve Readme
  CMakeLists.txt
  README.md
  examples/example.json
  examples/minimal/CMakeLists.txt
  examples/minimal/main.cpp
  repl/repl.cpp
  simfil-language.md
Labels: docs :book:, enhancement :star2:

#46 Do not Build Repl if Building as Dependency
  CMakeLists.txt
Labels: enhancement :star2:, ci :robot:

#44 Implement geo function for geomtry collections
  README.md
  include/simfil/model/nodes.h
  src/ext-geo.cpp
  test/ext-geo.cpp
Labels: enhancement :star2:

#49 Do not allow zero Geometry capacity
  src/model/model.cpp
  src/model/nodes.cpp
Labels: bug :bug:

#51 Collection of bugfixes
  include/simfil/model/fields.h
  include/simfil/model/model.h
  include/simfil/model/nodes.h
  src/model/nodes.cpp
  test/ext-geo.cpp
Labels: bug :bug:
